#ifndef XVTF_ERROR_H__
#define XVTF_ERROR_H__

#define XVTF_SETERROR( CONTAINER, CODE) \
if (CONTAINER != nullptr) *CONTAINER = (unsigned int)CODE

namespace xvtf
{
	//----------------------------------------------------------------------------------------------------
	/// Contains all error codes that can be generated by the library.
	//----------------------------------------------------------------------------------------------------
	enum class ERRORCODE
	{
		UNKNOWN = 0xFF, /* An unknown error. */
		NONE = 0x0, /* No error occured */

		/* General errors */
		REQUIRED_PARAMETER_NULL = 0x1, /* A required parameter was null. */
		SYSTEM_FILE_ERROR = 0x2, /* An error occured trying to retrieve the file descriptor. */

		/* Image related errors */
		REQUESTED_IMAGE_DNE = 0x10, /* The requested image does not exist for the given file. */
		REQUESTED_RESOURCE_DNE = 0x11, /* The requested resource does not exist for the given file. */
		NOT_A_VTF_FILE = 0x12, /* Supplied file is not a VTF file. */
		UNSUPPORTED_FILE_VERSION = 0x13, /* Supplied file is not supported by the library. */
		HEADER_SIZE_TOO_LARGE = 0x14, /* The files given headersize is larger than the max possible size (usually this means data-corruption). */
		MISSING_IMAGE_DATA_MARKER = 0x15 /* Could not determine image starting location from header. */
	};
}

#endif // !XVTF_ERROR_H__
